### ISSUE TITLE
API Endpoint: 'Statistics'

### ISSUE THREAD

**Issue by LancePants97** [frien-emies/users_BE#7]
Request:
POST /api/v1/users/1/statistics (this may change, need to talk to games team)
Content-Type: application/json
Accept: application/json

USERS:
User 1: (id: 1, username: "bob", email: "bob@turing.com", password: "ihateruby", avatar: "image1_string_goes_here.jpg")
User 2: (id: 2, username: "rob", email: "rob@turing.com", password: "iloveruby", avatar: "image2_string_goes_here.jpg")

GAMES: 
Game 1: (id: 1, name: "chess", avatar: "image1_string_goes_here.jpg")
Game 2: (id: 2, name: "chess 2: this time its personal", avatar: "image2_string_goes_here.jpg")

**Comment by AustinKCodes** [comment]
*Cut for time contraints*
